name: Build Static App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: checkout-code
      uses: actions/checkout@v3.0.0

    - name: setup-dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: build-builder
      run: dotnet build ./_src/Blog.Builder.sln

    - name: publish-builder
      run: dotnet publish ./_src/Blog.Builder.sln --output tmp

    - name: build-output
      run: |
           cd tmp
           dotnet Blog.Builder.dll --workables ../workables --output ../_output

    - name: push-output
      run: |
           cd _output
           branchname=feature/build-$(date +"%Y.%m.%d-%H.%M.%S")-${{ github.run_number }}
           git config user.name  ${{ github.actor }}
           git config user.email  ${{ github.actor }}@github.com
           git branch ${branchname}
           git push --set-upstream origin ${branchname}
           git checkout ${branchname}
           git add .
           git commit --allow-empty -m "Automated static files build "
           git push

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: '[New Output] A user has added new content that is ready to be published.',
            owner,
            repo,
            head: '${{ github.ref_name }}',
            base: 'develop',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
          github.rest.issues.addLabels({
            owner,
            repo,
            issue_number: result.data.number,
            labels: ['feature', 'automated pr']
          });
